### ISSUE TITLE
Add Infro PR Checks?

### ISSUE THREAD

**Issue by colethienes** [M0NsTeRRR/homelabv3-infra#419]
I noticed that this repo uses Argo CD, and I thought I’d let you know that I recently released a Github app called Infro that several companies use internally that allows Argo CD users to preview Kubernetes changes in Github pull requests before they merge. I’m providing it for free to open source projects ([here’s](https://github.com/broersma-forslund/homelab/pull/158#issuecomment-1962289857) an example in the wild). [Here’s](https://medium.com/@colethienes/argocd-pull-request-checks-c863190c5f8c?source=friends_link&sk=2eda79520de33483591448c6dfe8d284) a setup guide with links to documentation. It’s in early stages, so I’m sure there will be warts. All feedback is welcome!

**Comment by M0NsTeRRR** [comment]
Hello,

Thank you for your proposal, but I'm not interested in adding this software for the following reasons:

- It's not open source, and 99% of my applications are open source.
- It can't be self-hosted, and I only use on-premises software that I manage myself, which is the objective of my homelab.
- I avoid exposing unnecessary applications like ArgoCD on the web.
- As stated in my documentation, I will not use any services that do not respect GDPR (except for some like GitHub) and you use Google Cloud to host your application.
- Opening issues without reading the GitHub and the project doesn't encourage me to use your tool. As I've observed on your GitHub, there's one issue per minute with the same copy/paste.
- When I come across a GitHub app that requires "Act on your behalf," it's an absolute no for me. If an application requests this, I believe it doesn't prioritize security.

I wish you all the best with your project.

**Comment by colethienes** [comment]
Thanks for the feedback!

> It's not open source, and 99% of my applications are open source.

I think I will most likely do this! If I do, would it be useful to you to open source a Github action or Github app. Maybe not since you don't want to expose the Argo CD endpoint?

> I avoid exposing unnecessary applications like ArgoCD on the web.
Just curious - how do you access the UI? VPN?

Cheers

**Comment by M0NsTeRRR** [comment]
No, that won't change anything. The criteria I mentioned above are prerequisites (self hosting etc...) and a github action can't access my LAN.
Yes I have a VPN to access it.

**Comment by colethienes** [comment]
Open sourced and added a[ self-hosting](https://github.com/infro-io/infro-core) option!
